---
title: "Multiple regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(plotly)
```

Data was taken from: http://archive.ics.uci.edu/ml/datasets/Air+Quality

```{r}
airq_data <- read.table('/home/marina/AirQualityUCI.csv', sep = ';', header = TRUE, dec = ",")
airq_data <- airq_data %>% select_if(~sum(!is.na(.)) > 0)  %>% drop_na()
airq_data[c('CO.GT.', 'C6H6.GT.', 'T', 'RH', 'AH')] <-  sapply(airq_data[c('CO.GT.', 'C6H6.GT.', 'T', 'RH', 'AH')], as.numeric)
airq_data <- airq_data[, c(3:15)]
airq_data <- sapply(airq_data, function(x){ifelse (x == -200, NA, x)})
airq_data <- as.data.frame(airq_data)
```

• Making the best model and predicting the values

```{r}
airq_data$PT08.S2.NMHC. <- (airq_data$PT08.S2.NMHC.)^-1 * (-1)
airq_data$PT08.S5.O3. <- (airq_data$PT08.S5.O3.)^-1 * (-1)
final_model <- lm(PT08.S3.NOx. ~ PT08.S2.NMHC. + PT08.S5.O3., data = airq_data, na.action = na.exclude)
```

• Prediction:

```{r warning=FALSE}
test_subset_multiple <-  airq_data[which(row.names(airq_data) %in% sample(row.names(airq_data), 200, replace = FALSE)), c(5,10,7)]
test_multiple <- data.frame(PT08.S2.NMHC. = test_subset_multiple$PT08.S2.NMHC., PT08.S5.O3. = test_subset_multiple$PT08.S5.O3.)
test_subset_multiple$pred_PT08.S3.NOx. <- predict(final_model, newdata = test_multiple)
colnames(test_subset_multiple) <- c('real_PT08.S2.NMHC.','real_PT08.S5.O3.', 'real_PT08.S3.NOx.', 'pred_PT08.S3.NOx.')
df <- data.frame('y' = airq_data$PT08.S3.NOx. , 'x1' = airq_data$PT08.S2.NMHC., 'x2' = airq_data$PT08.S5.O3.)

### Estimation of the regression plane
mod <- lm(y ~ x1+x2, data = df)
cf.mod <- coef(mod)
df <- df %>% drop_na()
### Calculate z on a grid of x-y values
PT08.S2.NMHC. <- seq(min(df$x1),max(df$x1),length.out=25)
PT08.S5.O3. <- seq(min(df$x2),max(df$x2),length.out=25)
z <- t(outer(PT08.S2.NMHC., PT08.S5.O3., function(x,y) cf.mod[1]+cf.mod[2]*x+cf.mod[3]*y))
#### Draw the plane with "plot_ly" and add points with "add_trace"

R <- round(summary(final_model)$adj.r.squared, digits = 3)
p <- round(summary(final_model)$coefficients[2,4], digits = 3)
titl <- paste('R^2 =', as.character(R),', p-val =', as.character(p))
 

plot_ly(x=~PT08.S2.NMHC., y=~PT08.S5.O3., z=~z, type="surface", opacity=0.7)  %>%
  add_trace(data = test_subset_multiple, x = ~ real_PT08.S2.NMHC., y = ~ real_PT08.S5.O3., 
            z = ~  pred_PT08.S3.NOx., type="scatter3d", size = 1, name= "Predicted", opacity=0.8) %>%
  add_trace(data = test_subset_multiple, x = ~ real_PT08.S2.NMHC., y = ~ real_PT08.S5.O3., 
            z = ~  real_PT08.S3.NOx., type="scatter3d", size = 1, name="Real", opacity=0.8) %>% 
  layout(title = titl)
```
  
